version: "3"

services:
  app:
    build: .
    container_name: api_app
    command: yarn run dev
    ports:
      - "3000:5001"
    volumes:
      - .:/usr/app
  db:
    image: mysql
    container_name: api_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PWRD}
      MYSQL_DATABASE: ${DB_DBSA}
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped